needed_codes = {
	# Translators: An option to automatically detect source language for translation.
	"auto":"Automatically detect language",
	# Translators: The name of a language supported by this add-on.
	"ceb":"Cebuano",
	# Translators: The name of a language supported by this add-on.
	"eo":"Esperanto",
	# Translators: The name of a language supported by this add-on.
	"haw":"Hawaiian",
	# Translators: The name of a language supported by this add-on.
	"hmn":"Hmong",
	# Translators: The name of a language supported by this add-on.
	"ht":"Creole Haiti",
	# Translators: The name of a language supported by this add-on.
	"jv":"Javanese",
	# Translators: The name of a language supported by this add-on.
	"ku":"Kurdish",
	# Translators: The name of a language supported by this add-on.
	"la":"Latin",
	# Translators: The name of a language supported by this add-on.
	"mg":"Malagasy",
	# Translators: The name of a language supported by this add-on.
	"my":"Myanmar (Burmese)",
	# Translators: The name of a language supported by this add-on.
	"ny":"Chichewa",
	# Translators: The name of a language supported by this add-on.
	"sd":"Sindhi",
	# Translators: The name of a language supported by this add-on.
	"sm":"Samoan",
	# Translators: The name of a language supported by this add-on.
	"sn":"Shona",
	# Translators: The name of a language supported by this add-on.
	"so":"Somali",
	# Translators: The name of a language supported by this add-on.
	"st":"Sesotho",
	# Translators: The name of a language supported by this add-on.
	"su":"Sundanese",
	# Translators: The name of a language supported by this add-on.
	"tl":"Tagalog",
	# Translators: The name of a language supported by this add-on.
	"yi":"Yiddish",
}

langcodes = [
	"auto",
	"af",
	"am",
	"ar",
	"az",
	"be",
	"bg",
	"bn",
	"bs",
	"ca",
	"ceb",
	"co",
	"cs",
	"cy",
	"da",
	"de",
	"el",
	"en",
	"eo",
	"es",
	"et",
	"eu",
	"fa",
	"fi",
	"fr",
	"fy",
	"ga",
	"gd",
	"gl",
	"gu",
	"ha",
	"haw",
	"he",
	"hi",
	"hmn",
	"hr",
	"ht",
	"hu",
	"hy",
	"id",
	"ig",
	"is",
	"it",
	"ja",
	"jv",
	"ka",
	"kk",
	"km",
	"kn",
	"ko",
	"ku",
	"ky",
	"la",
	"lb",
	"lo",
	"lt",
	"lv",
	"mg",
	"mi",
	"mk",
	"ml",
	"mn",
	"mr",
	"ms",
	"mt",
	"my",
	"ne",
	"nl",
	"no",
	"ny",
	"or",
	"pa",
	"pl",
	"ps",
	"pt",
	"ro",
	"ru",
	"rw",
	"sd",
	"si",
	"sk",
	"sl",
	"sm",
	"sn",
	"so",
	"sq",
	"sr",
	"st",
	"su",
	"sv",
	"sw",
	"ta",
	"te",
	"tg",
	"th",
	"tk",
	"tl",
	"tr",
	"tt",
	"ug",
	"uk",
	"ur",
	"uz",
	"vi",
	"xh",
	"yi",
	"yo",
	"zh-CN",
	"zh-TW",
	"zu",
]
